// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRelation = "relations"

// Relation mapped from table <relations>
type Relation struct {
	ID         int64          `gorm:"column:id;primaryKey" json:"id"`        // 主键ID
	ToUserID   int64          `gorm:"column:to_user_id" json:"to_user_id"`   // 被关注用户ID
	FollowerID int64          `gorm:"column:follower_id" json:"follower_id"` // 关注用户ID
	CreatedAt  time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Relation's table name
func (*Relation) TableName() string {
	return TableNameRelation
}
