// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 主键ID
	Username      string         `gorm:"column:username" json:"username"`                   // 用户名
	Password      string         `gorm:"column:password" json:"password"`                   // 密码
	FollowCount   int64          `gorm:"column:follow_count" json:"follow_count"`           // 关注总数
	FollowerCount int64          `gorm:"column:follower_count" json:"follower_count"`       // 粉丝总数
	CreatedAt     time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
