// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameChat = "chat"

// Chat mapped from table <chat>
type Chat struct {
	ID         int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 主键ID
	FromUserID int64          `gorm:"column:from_user_id" json:"from_user_id"`           // 发送消息用户ID
	ToUserID   int64          `gorm:"column:to_user_id" json:"to_user_id"`               // 接收消息用户ID
	Content    string         `gorm:"column:content" json:"content"`                     // 消息内容
	CreatedAt  time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Chat's table name
func (*Chat) TableName() string {
	return TableNameChat
}
