// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	chat "gitee.com/derrickball/douyin/app/api/biz/router/chat"
	comment "gitee.com/derrickball/douyin/app/api/biz/router/comment"
	favorite "gitee.com/derrickball/douyin/app/api/biz/router/favorite"
	relation "gitee.com/derrickball/douyin/app/api/biz/router/relation"
	user "gitee.com/derrickball/douyin/app/api/biz/router/user"
	video "gitee.com/derrickball/douyin/app/api/biz/router/video"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	chat.Register(r)

	video.Register(r)

	user.Register(r)

	relation.Register(r)

	favorite.Register(r)

	comment.Register(r)
}
